-- statement 01
SELECT booking_reminders.id, booking_reminders.booking_id, booking_reminders.rule_id, booking_reminders.kind, booking_reminders.scheduled_for, booking_reminders.sent_at, booking_reminders.status, booking_reminders.attempt_count, booking_reminders.error, booking_reminders.created_at FROM booking_reminders JOIN bookings ON booking_reminders.booking_id = bookings.id LEFT OUTER JOIN reminder_rules ON booking_reminders.rule_id = reminder_rules.id WHERE booking_reminders.scheduled_for <= ? AND bookings.status = ? AND (booking_reminders.status = ? AND (booking_reminders.sent_at IS NULL OR booking_reminders.sent_at <= ?) OR booking_reminders.status = ? AND coalesce(booking_reminders.attempt_count, ?) < coalesce(reminder_rules.max_sends, ?)) ORDER BY booking_reminders.scheduled_for ASC, booking_reminders.id ASC LIMIT ? OFFSET ?;

-- statement 02
SELECT reminder_rules.id AS reminder_rules_id, reminder_rules.name AS reminder_rules_name, reminder_rules.enabled AS reminder_rules_enabled, reminder_rules.offset_minutes_before AS reminder_rules_offset_minutes_before, reminder_rules.max_sends AS reminder_rules_max_sends, reminder_rules.min_minutes_between_sends AS reminder_rules_min_minutes_between_sends, reminder_rules.template_name AS reminder_rules_template_name, reminder_rules.channel AS reminder_rules_channel, reminder_rules.created_at AS reminder_rules_created_at, reminder_rules.updated_at AS reminder_rules_updated_at FROM reminder_rules WHERE reminder_rules.id = ?;

-- statement 03
SELECT bookings.id AS bookings_id, bookings.ref AS bookings_ref, bookings.customer_phone AS bookings_customer_phone, bookings.customer_vehicle_id AS bookings_customer_vehicle_id, bookings.status AS bookings_status, bookings.customer_name AS bookings_customer_name, bookings.vehicle_type AS bookings_vehicle_type, bookings.car_model AS bookings_car_model, bookings.color AS bookings_color, bookings.service_id AS bookings_service_id, bookings.service_bucket AS bookings_service_bucket, bookings.service_label AS bookings_service_label, bookings.price_dh AS bookings_price_dh, bookings.price_regular_dh AS bookings_price_regular_dh, bookings.promo_code AS bookings_promo_code, bookings.promo_label AS bookings_promo_label, bookings.location_mode AS bookings_location_mode, bookings.center AS bookings_center, bookings.center_id AS bookings_center_id, bookings.geo AS bookings_geo, bookings.address AS bookings_address, bookings.address_text AS bookings_address_text, bookings.location_name AS bookings_location_name, bookings.location_address AS bookings_location_address, bookings.latitude AS bookings_latitude, bookings.longitude AS bookings_longitude, bookings.date_label AS bookings_date_label, bookings.slot AS bookings_slot, bookings.appointment_date AS bookings_appointment_date, bookings.slot_id AS bookings_slot_id, bookings.note AS bookings_note, bookings.addon_service AS bookings_addon_service, bookings.addon_service_label AS bookings_addon_service_label, bookings.addon_price_dh AS bookings_addon_price_dh, bookings.total_price_dh AS bookings_total_price_dh, bookings.appointment_start_at AS bookings_appointment_start_at, bookings.appointment_end_at AS bookings_appointment_end_at, bookings.timezone_name AS bookings_timezone_name, bookings.client_request_id AS bookings_client_request_id, bookings.source AS bookings_source, bookings.raw_booking_json AS bookings_raw_booking_json, bookings.created_at AS bookings_created_at, bookings.updated_at AS bookings_updated_at FROM bookings WHERE bookings.id = ?;

-- statement 04
UPDATE booking_reminders SET sent_at=?, attempt_count=? WHERE booking_reminders.id = ?;
